//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_SOAP_licenses
{
    using System;
    using System.Collections.Generic;
    
    public partial class license
    {
        public int lic_id { get; set; }
        public int lic_cmpid { get; set; }
        public bool lic_valid { get; set; }
    
        public virtual company company { get; set; }
    }
}
