//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_SOAP_licenses
{
    using System;
    using System.Collections.Generic;
    
    public partial class version
    {
        public int ver_id { get; set; }
        public string ver_name { get; set; }
        public string ver_version { get; set; }
    }
}
